### ISSUE TITLE
[BUG]  Euronews missing url base

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#160] opened 2022-09-29 20:30 UTC
### What bug did you encounter?

Going to the single source route for `Euronews` I noticed that the URLs provided are in need of a base.

### What did you expect to happen?

A full URL to be returned so that a user of the API can link directly to the article found.

### Screenshots

![image](https://user-images.githubusercontent.com/90829439/193134916-cdbfaa40-9086-419a-8621-ccfe79c0b9f6.png)

### Additional information

Current url example:

"/2022/09/17/this-1373km-long-undersea-cable-will-bring-green-energy-from-egypt-to-europes-electricity-"

Have a look in the `src/data/sources.json` file and see how some of the other sources have a `"base"`. Make and test one that makes the returned URLs work.

**Comment by ashwin-acharya01** [comment] 2022-09-30 08:28
@MizouziE can I work on this? I haven't really contributed to any project previously so could you guide me

**Comment by MizouziE** [comment] 2022-09-30 08:54
@ashwin-acharya01 Sure thing. I'll assign you and feel free to ask any questions that you have. 

Are u comfortable with forking the repo and opening a new branch?

After that, make the changes u want, commit and push them to your remote branch and then open a pull request from your branch to the main branch on this repo. 

Honestly ask as many questions as you need because it will help me to write better documentation for future contributors.

**Comment by TAKANOME-DEV** [comment] 2022-09-30 09:13
@MizouziE we definitely need to add the `CONTRIBUTING` file, feel free to take #29 :bulb:  it's been 4 months and there is no updates on that :thinking:

**Comment by ashwin-acharya01** [comment] 2022-09-30 17:51
@MizouziE Thanks for assigning me this issue. 
When I tried running npm run dev I'm actually getting this error

[nodemon] app crashed - waiting for file changes before starting...

I did try searching for it but feel kinda stuck.

**Comment by MizouziE** [comment] 2022-09-30 17:57
Hi @ashwin-acharya01 two questions:

1. Has `npm install` been run?
2. Can you give a screenshot or just copy/paste the last 20 or so lines of the error message in the terminal?

It may be that the twitter route is still acting up and I haven't yet merged the fix for it.

**Comment by ashwin-acharya01** [comment] 2022-09-30 18:07
Yes I did run npm install
And the error message is pretty big but here I've attached some screenshots of the same
<img width="516" alt="image" src="https://user-images.githubusercontent.com/87590123/193330176-63e44929-8a52-4d84-b86a-ee04d5ce8262.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/87590123/193330511-dd45c57a-dc5f-4d1c-9335-5ac3e229c4eb.png">

**Comment by TAKANOME-DEV** [comment] 2022-09-30 18:17
@ashwin-acharya01 kill and restart the server, this error is caused by the twitter endpoint and was suppose to be fixed by #162 :thinking: 
Dont worry about the error, try restarting the server and make sure that your fork is up to date

**Comment by MizouziE** [comment] 2022-09-30 18:25
Yes I must apologise for not fixing this properly, but the fix **is** in the PR I am in the process of submitting.

Like @TAKANOME-DEV said, restarting the server once or twice usually gets rid of this error, but if it persists beyond that you can comment out line 5 of `src/server.js` as [I did here on the soon to be merged branch](https://github.com/Energy-Price-News-API/energy-prices-api/pull/165/commits/0d301ce005bcd2f344c1ce9cd66596bf900c990c).

**Comment by TAKANOME-DEV** [comment] 2022-09-30 18:46
Everything is working fine for me :thinking: and @MizouziE did fix that, try to update your repo:
- the easy way is to go on your forked repo on github, you should see that your branch is behind upstream, just hit `sync fork`  and `update branch`
- open the project in your terminal and type: `git fetch origin`
- `git merge origin/master`

**Comment by MizouziE** [comment] 2022-09-30 18:55
> Everything is working fine for me :thinking: and @MizouziE did fix that, try to update your repo:
> 
> - the easy way is to go on your forked repo on github, you should see that your branch is behind upstream, just hit `sync fork`  and `update branch`
> 
> - open the project in your terminal and type: `git fetch origin`
> 
> - `git merge origin/master`

It's been popping up for me today which is why I made an extra change in this newest PR. 

The scrape job was still going ahead even though the endpoint was removed. 

Should have it all ready soon, just got some tests to write and it's complete.

**Comment by ashwin-acharya01** [comment] 2022-10-01 04:10
@TAKANOME-DEV  @MizouziE  Thanks for the help. It's up and running. 

Is this the expected result?
<img width="806" alt="image" src="https://user-images.githubusercontent.com/87590123/193388797-be18c37e-eb5f-424f-95e1-cecce662245e.png">

**Comment by MizouziE** [comment] 2022-10-01 09:06
It absolutely is! In all it's JSON glory 😂😂

Happy coding!

**Comment by shreyas2711** [comment] 2022-10-01 17:35
Can I take up this issue? I will be happy to contribute :)

**Comment by TAKANOME-DEV** [comment] 2022-10-01 18:39
Hi @shreyas2711 , thanks for taking an interest in the project!
This issue has been already taken by @ashwin-acharya01

Please take a look at our [issues here](https://github.com/Energy-Price-News-API/energy-prices-api/issues), there are plenty of `good-first-issue` that you can pick up and start contributing :rocket: 

Feel free to ask any questions, we will get back to you as soon as we can

**Closed** 2022-10-05 15:21 UTC
Labels: :beers:  good first issue, first timers only
