### ISSUE TITLE
Test: Add a test suite for `api/news/regions`

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#151] opened 2022-09-25 21:48 UTC
### What would you like to share?

Add a test suite for the `regions` endpoints.
### Steps:
- Add a new `describe block` for `/api/news/sources` inside `/__tests__/integration-tests/routes/news.test.js`
- Add test suite for all possible scenarios

### Additional information

> **Note**
> All `axios` requests are mock inside the `__mocks__` folder
> Fell free to add more mock data inside that file

**Comment by reny-pacheco** [comment] 2022-10-06 14:51
Hi there, Please assign this to me. I would like to contribute to this repo by adding tests. This is my starting point to contribute to open source project. Thanks

**Closed** 2022-10-06 17:47 UTC
Labels: :rescue_worker_helmet:  help wanted, :beers:  good first issue, :heavy_check_mark:   testing

**Comment by MizouziE** [comment] 2022-10-06 17:50
Thanks for getting involved and I appreciate the contribution. I've assigned you even thought it's closed and ur PR accepted and merged, but just to second what TAKANONE said, we try and stick to only accepting once assigned just to keep it fair for everyone, especially those trying to make a start in OSS. 

Glad to have you aboard all the same!

**Comment by reny-pacheco** [comment] 2022-10-06 22:42
Apologies for creating a PR even though the issue is not assigned to me. This is my first contribution to open source and I'm happy that my first PR has been merged. Thank you very much.

**Comment by MizouziE** [comment] 2022-10-07 06:14
No problem! 👊
